name: Python Stack Application CI

on:
  push:
    branches:
      - main
      - '**/feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manual trigger with input parameter
    inputs:
      target-file:
        description: 'Select the application file to run'
        required: true
        type: choice
        options:
          - modules/complete-stack-app/MainForStack.py
          - modules/wk2/Doubly-linked-list/main.py
          - modules/wk2/Singly-linked-list/main.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run selected application
      run: |
        python ${{ github.event.inputs.target-file }}
